Rename: Fhi.VersionApiClient.sln -> Fhi.Common.VersionApiClient.sln
FHIDev/Fhi.VersionApiClient pull request #10
Opened 2024-11-19 11:12 UTC by GeirMG

Merge before: https://github.com/FHIDev/Fhi.VersionApiClient/pull/9

2024-11-19 11:14 UTC, GeirMG commented
@OsirisTerje Should we rename the GitHub repo also, and update the README.md?

2024-11-20 14:48 UTC, OsirisTerje commented
> should we rename the GitHub repo also, and update the README.md?

sure!

2024-11-20 14:49 UTC, OsirisTerje requested changes

2024-11-20 14:49 UTC, OsirisTerje commented on Fhi.Common.VersionApiClient.sln
Navnet skal da være Fhi.VersionApiClient

2024-11-21 12:32 UTC, GeirMG commented
Replaced by: https://github.com/FHIDev/Fhi.VersionApiClient/pull/11

2024-11-21 12:32 UTC, closed without merging